port: "8000"

db:
    username: "postgres"
#    password: "qwerty"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"
#    dbpath: "user=postgres password=qwerty host=localhost dbname=postgres port=5432 sslmode=disable"